sudo: false

language: node_js

node_js: 8

cache:
  directories:
    - node_modules

branches:
  only: master

# Build steps
install:
  - npm install

script: true

deploy:
  provider: script
  skip_cleanup: true
  script:
    - npx -p semantic-release@15
