sudo: false

language: node_js

node_js: 8

install:
  - npm install

deploy:
  provider: script
  skip_cleanup: true
  script:
    - npx semantic-release

notifications:
  email: false
install: npm install
script:
  - npx -p semantic-release@15 -c "semantic-release --prepare && npm publish && semantic-release --success"
branches:
  only: master